<%@ Page Language="C#" AutoEventWireup="true" CodeFile="servdogovor.aspx.cs" Inherits="Docs_servdogovor" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>

<p align="center" style="background-image: initial; background-attachment: initial; background-color: white; text-align: center;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="text-decoration: none;">ДОГОВОР НА ОКАЗАНИЕ МЕДИЦИНСКИХ УСЛУГ</span></b><b> № </b>
    <asp:Label ID="_numberdog" runat="server"></asp:Label>
    </span></p>
<p align="center" style="text-align: center; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b></b></span><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b>&nbsp; г. Астрахань &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</b>«<asp:Label ID="_day" runat="server"></asp:Label>» <asp:Label ID="_month" runat="server"></asp:Label><asp:Label ID="_year" runat="server"></asp:Label>г.</span></p>
<p align="right" style="text-align: right; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b>&nbsp;</b></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">«<asp:Label ID="_namemo" runat="server"></asp:Label>
    »<span style="letter-spacing: -0.15pt;">, лицензия на право осуществления медицинской деятельности
    <asp:Label ID="_licenz" runat="server"></asp:Label>
    <span style="letter-spacing: -0.2pt;">, именуемое в дальнейшем «Исполни<span style="letter-spacing: -0.15pt;">тель», в лице 
    <asp:Label ID="_lico" runat="server"></asp:Label>
    , с одной стороны и&nbsp; (гр.) Ф.И.О.<asp:Label ID="_fiopac" runat="server"></asp:Label>
    , <span style="letter-spacing: -0.15pt;">именуемый в дальнейшем «Заказчик», с другой стороны, заключили настоящий Договор о ни<span style="letter-spacing: -0.65pt;">жеследующем:</span></span></span></span></span></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">&nbsp;</span></p>
<ol start="1" style="margin-top: 0cm;">
<li style="text-align: center; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.55pt;">Предмет Договора</span></b></span></li>
</ol>
<p style="margin-left: 18pt; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.55pt;">&nbsp;</span></b></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="color: #000000;"><span style="letter-spacing: -0.15pt; font-size: 12pt; font-family: 'times new roman', times;">1.1. Заказчик поручает, а Исполнитель обязуется оказывать на возмездной основе необходимую медицинскую <span style="letter-spacing: -0.2pt;">помощь (медицинские услуги, в том числе профилактические, лечебно-диагностические, <span style="letter-spacing: -0.25pt;">реабилитационные, ортопедотравматологические, и др.), отвечающую требованиям, предъявляемым к методам диагностики, профилактики и лечения, разрешенным на территории РФ,&nbsp; в условиях стационара Пациенту:&nbsp;</span></span></span><span style="letter-spacing: -0.25pt; font-size: 12pt; font-family: 'times new roman', times;">Ф.И.О.<asp:Label ID="_fiopac2" runat="server"></asp:Label>
    <span style="letter-spacing: -0.1pt;">Заказчик добровольно принимает на себя обязательство оплачивать оказанные медицинские <span style="letter-spacing: -0.2pt;">услуги (медицинскую помощь) в порядке и на условиях, предусмотренных настоящим Догово<span style="letter-spacing: -0.8pt;">ром.</span></span></span></span></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">&nbsp;</span></p>
<p align="center" style="margin-left: 36pt; text-align: center; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.5pt;">2. Права и обязанности Сторон</span></b></span></p>
<p align="center" style="margin-left: 36pt; text-align: center; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.5pt;">&nbsp;</span></b></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.5pt;">&nbsp;2.1.&nbsp; Заказчик (Пациент) имеет право:</span></b></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.1pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.1.1. Получать квалифицированные медицинские услуги (медицинскую помощь).</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.35pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.1.2. В любой момент отказаться от медицинской помощи&nbsp; с оплатой фактически оказанных услуг.</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.35pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.1.3. Заказчик имеет право на получение информации о стоимости оказанных услуг на любом этапе стационарного обследования и лечения (за исключением выходных и праздничных дней).</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.35pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.1.4. Получать сведения о квалификации и сертификации специалистов.</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.35pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.1.5. Самостоятельно, после согласования с лечащим врачом, приобретать расходные материалы и лекарственные средства, за качество которых исполнитель ответственности не несет. </span></p>
<p style="margin-left: 2.15pt; text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.35pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.1.6. Предъявлять требования о возмещении убытков, причиненных неисполнением или ненадлежащим исполнением условий договора, возмещении ущерба в случае причинения вреда здоровью и жизни в соответствии с законодательством РФ.</span></p>
<p style="margin-left: 18pt; text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">&nbsp;</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.25pt;">2.2. </span></b><span style="letter-spacing: -0.25pt;">&nbsp;<b>Заказчик (Пациент) обязуется:</b></span></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.1pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.2.1. Оплатить стоимость предоставляемой медицинской помощи (медицинских услуг), <span style="letter-spacing: 0.9pt;">сог<span style="letter-spacing: -0.25pt;">ласно Прейскуранта,&nbsp; действующего&nbsp; на момент заключения договора (госпитализации).</span></span></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.2pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.2.2. Выполнять требования, обеспечивающие качественное предоставление платных медицинских услуг, включая сообщение необходимых для этого сведений.</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.2pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.2.3.&nbsp; Возместить убытки в случае причинения ущерба пациентом имуществу Исполнителя.</span></p>
<p style="margin-left: 18pt; text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">&nbsp;</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.25pt;">2.3.</span></b><span style="letter-spacing: -0.25pt;"> <b>Исполнитель имеет право:</b></span></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.2pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.3.1. Определять длительность лечения, объем медицинских услуг,<span style="letter-spacing: -0.2pt;"> необходимость перевода в отделения другого профиля в соответствии с состоянием здоровья Пациента<span style="letter-spacing: -0.2pt;">;</span></span></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.2pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.3.<span style="letter-spacing: -0.2pt;">2<span style="letter-spacing: -0.2pt;">. В случае возникновения неотложных состояний, угрожающих жизни Пациента, самостоятельно определять объем иссле<span style="letter-spacing: -0.1pt;">дований, манипуляций, оперативных вмешательств, необходимых для установления диагноза, <span style="letter-spacing: -0.25pt;">обследования и оказания медицинской помощи. </span></span></span></span></span></p>
<p style="text-align: justify;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.3.3. При необходимости привлекать для оказания медицинских услуг сторонних исполнителей и соисполнителей по согласованию с Пациентом и Заказчиком;</span></p>
<p style="margin-left: 27pt; text-align: justify; text-indent: -27pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.3.4.Исполнитель имеет право расторгнуть договор при нарушении Пациентом правил внутреннего распорядка больницы. </span></p>
<p style="text-align: justify;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">&nbsp;</span></p>
<p style="text-align: justify;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.25pt;">&nbsp;</span></b></span></p>
<p style="text-align: justify;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.25pt;">2.4</span></b><span style="letter-spacing: -0.25pt;">. <b>Исполнитель обязан:</b></span></span></p>
<p style="text-align: justify;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.4.1.Ознакомить Пациента при поступлении в стационар с правилами внутреннего распорядка больницы.</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.05pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.4.2. Обеспечить соответствие предоставляемых по настоящему Договору услуг требованиям, <span style="letter-spacing: -0.15pt;">предъявляемым к методам диагностики, профилактики и лечения на территории <span style="letter-spacing: -0.25pt;">Российской Федерации;</span></span></span></p>
<p style="margin-left: 0.5pt; text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.2pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.4.3. Представлять счет-фактуру с указанием перечня и стоимости оказанных медицинских услуг;</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">&nbsp;</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.2pt;">2.5. Пациент имеет право:</span></b></span></p>
<p style="margin-left: 1.75pt; text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.2pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.5.1. Получать в доступной для него форме имеющуюся информацию о состоянии своего здоровья, включая сведения о результатах обследования, наличии заболевания, его диагнозе и прогнозе, методах лечения, связанном с ними риске, возможных вариантах медицинского вмешательства, их последствиях и результатах проведенного лечения.</span></p>
<p style="margin-left: 1.75pt; text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.2pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.5.2.Пациент имеет право на информированное добровольное согласие на медицинское вмешательство. В случаях, когда состояние Пациента не позволяет ему выразить свою волю, а медицинское вмешательство неотложно, вопрос о его проведении в интересах&nbsp; Пациента решает консилиум, а в особых случаях лечащий (дежурный) врач. Отказ от медицинского вмешательства с указанием возможных последствий оформляется записью в медицинской документации и подписывается пациентом или его законным представителем, а также врачом.</span></p>
<p style="margin-left: 18pt; text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.2pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">&nbsp;</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.2pt;">2.6. Пациент обязуется: </span></b></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.2pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.6.1. Ознакомиться с правилами внутреннего распорядка больницы и соблюдать их.</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.2pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.6.2. Выполнять назначения лечащего врача.</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.2pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.6.3. Сообщать лечащему врачу все сведения о состоянии своего здоровья</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.2pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">2.6.4. В случае любых изменений в состоянии здоровья немедленно сообщать об этом лечащему (дежурному) врачу. </span></p>
<p align="center" style="margin-left: 36pt; text-align: center; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.2pt;">3. Стоимость услуг и порядок расчётов</span></b></span></p>
<p align="center" style="margin-left: 36pt; text-align: center; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.2pt;">&nbsp;</span></b></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.2pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">3.1. Заказчик оплачивает медицинские услуги по Прейскуранту, утверждённому Исполнителем<span style="letter-spacing: -0.3pt;">; </span></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.3pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">3.2. Заказчик оплачивает 100% предварительную стоимость медицинских услуг. </span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.3pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">3.3. При&nbsp; заключении договора&nbsp; с 17-00 до 8-30, а&nbsp; также&nbsp; в выходные и праздничные дни заказчик оплачивает авансовую стоимость медицинских услуг в размере 
    <asp:Label ID="_cost" runat="server"></asp:Label>
    рублей, которую вносит в кассу в первый рабочий день, а оставшуюся часть суммы оплачивает после составления предварительной стоимости услуг.</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">3.4. Предварительная&nbsp;&nbsp; стоимость&nbsp; медицинских услуг по данному договору составляет 
    <asp:Label ID="_cost2" runat="server"></asp:Label>
    рублей. </span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">3.5. Стоимость услуг&nbsp; может быть увеличена по согласованию с&nbsp; Заказчиком в случае оказания Пациенту дополнительных медицинских услуг,&nbsp; в том числе и по просьбе Пациента.</span></p>
<p align="center" style="text-align: center; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.25pt;">4. Ответственность Сторон</span></b></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.25pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">4.1. Стороны несут ответственность за неисполнение или ненадлежащее исполнение условий настоящего договора в соответствии с законодательством&nbsp; Российской Федерации.</span></p>
<p style="margin-left: 18pt; text-align: justify; text-indent: -18pt;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">4.2.&nbsp;&nbsp; «Исполнитель» не несет ответственности в случаях:</span></p>
<p style="text-indent: -18pt; text-align: justify;"><span style="color: #000000;"><span style="font-size: 12pt; font-family: 'times new roman', times;">- возникновения осложнений по вине Пациента (невыполнение назначений врача, несвоевременное сообщение о возникших отклонениях и нарушениях в состоянии здоровья)</span><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="font-family: 'times new roman', times; font-size: 12pt;">;</span></span></span></p>
<p style="text-indent: -18pt; text-align: justify;"><span style="font-family: 'times new roman', times; font-size: 12pt; color: #000000;">- прекращения лечения по инициативе Пациента.</span></p>
<p style="text-align: justify;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">&nbsp;</span></p>
<p style="text-align: justify;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">&nbsp;</span></p>
<p align="center" style="text-align: center;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b>5. Конфиденциальность</b></span></p>
<p align="center" style="text-align: center;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b>&nbsp;</b></span></p>
<p style="text-align: justify;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">5.1. Исполнитель обязуется хранить в тайне информацию о факте обращения Пациента за медицинской помощью, состоянии его здоровья, диагнозе его заболевания и иные сведения, полученные при его обследовании и лечении. </span></p>
<p style="text-align: justify;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">5.2. С согласия Пациента или его законного представителя допускается передача сведений, составляющих врачебную тайну другим лицам, указанным Пациентом или его законным представителем. </span></p>
<p style="text-align: justify;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">5.3. Предоставление сведений, составляющих врачебную тайну, без согласия Пациента или его законного представителя допускается в случаях, установленных ст. 61 Основ законодательства РФ об охране здоровья граждан. </span></p>
<p align="center" style="text-align: center; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.3pt;">6. Сроки исполнения</span></b></span></p>
<p align="center" style="text-align: center; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.3pt;">&nbsp;</span></b></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.25pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">6.1. Настоящий договор вступает в силу с момента его подписания и внесения Заказчиком 100% предоплаты предварительной стоимости медицинских услуг<span style="letter-spacing: -0.2pt;"> и действителен до полного исполнения сторонами своих обязательств.</span></span></p>
<p align="center" style="text-align: center; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b><span style="letter-spacing: -0.25pt;">7. Дополнительные условия</span></b></span></p>
<p align="center" style="text-align: center; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.25pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">&nbsp;</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.15pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">7.1. Заказчик (Пациент) уведомлен о порядке получения медицинской помощи на территории Российской Федерации, а также о возможности получения бесплатной медицинской помощи, предусмотренной программами обязательного медицинского страхования. Заказчик (Пациент) согласен получить медицинскую помощь (медицинские услуги) в Клинической больнице № 83 на платной основе.</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.25pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">7.2. Сумма расходных материалов и лекарственных препаратов, приобретенных Заказчиком (Пациентом) самостоятельно, в счет оказанных медицинских услуг не включается.</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.25pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">7.3. Согласие Заказчика (Пациента) на проведение медицинской услуги и факт её получения одновременно означает и согласие Заказчика (Пациента) на оплату этой услуги.</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="letter-spacing: -0.25pt; font-size: 12pt; font-family: 'times new roman', times; color: #000000;">7.4. Все остальное, что не урегулировано настоящим Договором, регулируется законодательством Российской Федерации.</span></p>
<p align="center" style="text-align: center; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b>8. Рассмотрение споров</b></span></p>
<p align="center" style="text-align: center; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b>&nbsp;</b></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">При наличии претензии к проведенным обследованиям, консультациям специалистов, лечению и пр. (по мнению Пациента) Заказчик (Пациент) обязан в тот же день информировать о данном факте лечащего врача и/или заведующего отделением. Все споры по договору стороны стараются урегулировать в дружеском порядке путем переговоров. В случае невозможности урегулирования спора путем переговоров, спор подлежит разрешению в соответствии с действующим законодательством РФ в суде по месту нахождения Исполнителя.</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">&nbsp;</span></p>
<p align="center" style="text-align: center; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b>9. Реквизиты сторон</b></span></p>
<p align="center" style="text-align: center; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b>&nbsp;</b></span></p>
<p align="center" style="text-align: center; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">&nbsp;</span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b>Исполнитель:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Заказчик:</b></span></p>
<p style="text-align: justify; background-image: initial; background-attachment: initial; background-color: white;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><b>&nbsp;&nbsp; </b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
<p><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">Адрес: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><asp:Label ID="_fiozak" runat="server" Width="250px"></asp:Label>
            </p>
<p><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><asp:Label ID="_address" Width="280px" runat="server"></asp:Label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <asp:Label ID="_fiozak2" Width="250px" runat="server"></asp:Label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">тел.&nbsp;</span><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><asp:Label ID="_phone" Width="250px" runat="server"></asp:Label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Паспорт серия 
    <asp:Label ID="_passer" runat="server" Width="50px"></asp:Label>
    №<asp:Label ID="_pasnom" Width="70px" runat="server"></asp:Label></span></p>
<p><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">ИНН</span><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><asp:Label ID="_inn" Width="250px" runat="server"></asp:Label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Выдан &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p>
<p><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">КПП</span><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><asp:Label ID="_kpp" Width="250px" runat="server"></asp:Label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
    <asp:Label ID="_vidan" runat="server" Width="250px"></asp:Label>
            </p>
<p><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;">БИК</span><span style="font-size: 12pt; font-family: 'times new roman', times; color: #000000;"><asp:Label ID="_bik" Width="250px" runat="server"></asp:Label></span></p>
<p>&nbsp;</p>

			

        </div>
    </form>
</body>
</html>
